import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronLeft, ChevronRight, Plus, ShieldCheck, Cloud, CloudOff, Menu, UserCircle2, } from 'lucide-react';
import { periodoLabel } from '../lib/periodoUtils';
export const Header = ({ periodo, onPrev, onNext, onToday, onNewWeek, onOpenSecurity, onOpenMobileMenu, username, isSyncing, isOnline, }) => {
    const label = periodoLabel(periodo);
    return (_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-2", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { onClick: onOpenMobileMenu, className: "lg:hidden p-1.5 rounded-xl text-[#888] hover:text-[#2F3332] hover:bg-white border border-transparent hover:border-[#E0DED9] transition-all cursor-pointer", children: _jsx(Menu, { className: "w-5 h-5" }) }), _jsxs("div", { className: "flex items-center gap-1 bg-white border border-[#E0DED9] rounded-2xl px-2 py-1.5 shadow-2xs", children: [_jsx("button", { onClick: onPrev, className: "p-1 rounded-lg text-[#888] hover:text-[#2F3332] hover:bg-[#FAF9F7] transition-colors cursor-pointer", title: "Periodo precedente", children: _jsx(ChevronLeft, { className: "w-4 h-4" }) }), _jsx("div", { className: "px-3 text-center min-w-[180px]", children: _jsx("span", { className: "text-xs font-bold text-[#2F3332] tracking-wide", children: label }) }), _jsx("button", { onClick: onNext, className: "p-1 rounded-lg text-[#888] hover:text-[#2F3332] hover:bg-[#FAF9F7] transition-colors cursor-pointer", title: "Periodo successivo", children: _jsx(ChevronRight, { className: "w-4 h-4" }) })] }), _jsx("button", { onClick: onToday, className: "hidden sm:inline-flex items-center px-3 py-1.5 rounded-xl bg-white border border-[#E0DED9] text-xs font-bold text-[#5B6760] hover:bg-[#FAF9F7] transition-colors cursor-pointer shadow-2xs", children: "Oggi" })] }), _jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsxs("div", { className: `hidden sm:flex items-center gap-1.5 px-2.5 py-1.5 rounded-xl border text-[11px] font-bold transition-colors ${isSyncing
                            ? 'bg-amber-50 border-amber-200 text-amber-700'
                            : isOnline
                                ? 'bg-[#EBF1ED] border-[#D5E1D9] text-[#3E5949]'
                                : 'bg-stone-50 border-stone-200 text-stone-500'}`, title: isSyncing ? 'Sincronizzazione in corso…' : isOnline ? 'Dati sincronizzati' : 'Offline – dati in locale', children: [isOnline ? (_jsx(Cloud, { className: `w-3.5 h-3.5 ${isSyncing ? 'animate-pulse' : ''}` })) : (_jsx(CloudOff, { className: "w-3.5 h-3.5" })), _jsx("span", { className: "hidden md:inline", children: isSyncing ? 'Sincronizzazione…' : isOnline ? 'Sincronizzato' : 'Offline' })] }), _jsxs("div", { className: "flex items-center gap-1.5 px-2.5 py-1.5 bg-[#EBF1ED] rounded-xl border border-[#D5E1D9] text-xs font-bold text-[#3E5949]", children: [_jsx(UserCircle2, { className: "w-4 h-4" }), _jsx("span", { className: "hidden sm:inline", children: username })] }), _jsxs("button", { id: "btn-security", onClick: onOpenSecurity, className: "flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white border border-[#E0DED9] text-xs font-bold text-[#5B6760] hover:bg-[#FAF9F7] transition-colors cursor-pointer shadow-2xs", title: "Sicurezza & Privacy", children: [_jsx(ShieldCheck, { className: "w-4 h-4" }), _jsx("span", { className: "hidden sm:inline", children: "Sicurezza" })] }), _jsxs("button", { id: "btn-new-week", onClick: onNewWeek, className: "flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-[#7C8B82] hover:bg-[#68766E] text-white text-xs font-bold uppercase tracking-wider transition-colors cursor-pointer shadow-xs", children: [_jsx(Plus, { className: "w-4 h-4" }), _jsx("span", { children: "Nuovo" })] })] })] }));
};
